### PR TITLE
wip

### PR DESCRIPTION
**Pull request by xeno-by**

### CODE REVIEW

**Comment by xeno-by** [comment]
Test

**Comment by rscbenchbox** [comment]
Beep boop

**Comment by rscbenchbox** [comment]
test

**Comment by rscbenchbox** [comment]
test

**Comment by rscbenchbox** [comment]
test

**Comment by rscbenchbox** [comment]
Accepted benchmarking [5bbdc87](https://github.com/xeno-by/reasonable-scala/commit/5bbdc877bb8e5a5e7643c149dde930bdb1856020). This may take a while.

**Comment by rscbenchbox** [comment]
Accepted benchmarking [1f17fc6](https://github.com/xeno-by/reasonable-scala/commit/1f17fc6b4b6d29f546c56d55c3e77e182a8899db). This may take a while.

**Comment by rscbenchbox** [comment]
Accepted benchmarking [1f17fc6](https://github.com/xeno-by/reasonable-scala/commit/1f17fc6b4b6d29f546c56d55c3e77e182a8899db). This may take a while.

**Comment by rscbenchbox** [comment]
Accepted benchmarking [b5ac90a](https://github.com/xeno-by/reasonable-scala/commit/b5ac90ae77d367976883a9f7e9c0b3fd446aa1a0). This may take a while.

**Comment by rscbenchbox** [comment]
Accepted benchmarking [ec93310](https://github.com/xeno-by/reasonable-scala/commit/ec93310c3a4097120eb1fd17bc4e1e15ef898823). This may take a while.

**Comment by rscbenchbox** [comment]
Accepted benchmarking [5c33425](https://github.com/xeno-by/reasonable-scala/commit/5c33425cf41d16e5337171c90fae13bbbca6fdd8). This may take a while.

**Comment by rscbenchbox** [comment]
Finished benchmarking [5c33425](https://github.com/xeno-by/reasonable-scala/commit/5c33425cf41d16e5337171c90fae13bbbca6fdd8).

                    | Benchmark          | Before | After |
                    |--------------------|--------|-------|
                    | RscNativeTypecheck | 63.438 ms     | 63.389 ms    |
                    | RscTypecheck       | 24.922 ms     | 25.181 ms    |

                    Full results are available at https://github.com/xeno-by/reasonable-scala/commit/321e103571a172fc623f1446150ec56d45fd29c8.

**Comment by rscbenchbox** [comment]
Accepted benchmarking [5c33425](https://github.com/xeno-by/reasonable-scala/commit/5c33425cf41d16e5337171c90fae13bbbca6fdd8). This may take a while.

**Comment by rscbenchbox** [comment]
Finished benchmarking [5c33425](https://github.com/xeno-by/reasonable-scala/commit/5c33425cf41d16e5337171c90fae13bbbca6fdd8).

                 | Benchmark          | Before | After |
                 |--------------------|--------|-------|
                 | RscNativeTypecheck | 63.438 ms     | 63.389 ms    |
                 | RscTypecheck       | 24.922 ms     | 25.181 ms    |

                 Full results are available at https://github.com/xeno-by/reasonable-scala/commit/5e3f22ecd960f06569aaf9cc7482b9c34429a804.

**Comment by rscbenchbox** [comment]
Finished benchmarking [5c33425](https://github.com/xeno-by/reasonable-scala/commit/5c33425cf41d16e5337171c90fae13bbbca6fdd8).

| Benchmark          | Before | After |
|--------------------|--------|-------|
| RscNativeTypecheck | 63.438 ms     | 63.389 ms    |
| RscTypecheck       | 24.922 ms     | 25.181 ms    |

Full results are available at https://github.com/xeno-by/reasonable-scala/commit/e0dac92049533904d22f1e7f67d563ef682c3fd3.

**Pull request closed without merging**
